#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));

function log(msg) {
  console.log(`[release] ${msg}`);
}

function fail(msg) {
  console.error(`[release] ERROR: ${msg}`);
  process.exit(1);
}

function getVersionArg() {
  const version = process.argv[2];
  if (!version) {
    fail('Missing version argument. Usage: npm run release -- 1.2.3');
  }

  // Basic semver-ish validation (allows pre-release tags)
  if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z-.]+)?$/.test(version)) {
    fail(`Invalid version "${version}". Expected format: X.Y.Z or X.Y.Z-tag`);
  }

  return version;
}

function updatePackageJson(version) {
  const pkgPath = resolve(ROOT, 'package.json');
  const pkgRaw = readFileSync(pkgPath, 'utf8');
  const pkg = JSON.parse(pkgRaw);

  const prev = pkg.version;
  pkg.version = version;

  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
  log(`Updated package.json version: ${prev} -> ${version}`);
}

function updateAndroidVersion(version) {
  const gradlePath = resolve(ROOT, 'android', 'app', 'build.gradle');
  let gradle = readFileSync(gradlePath, 'utf8');

  const versionNameRegex = /(versionName\s+")([^"]*)(")/;
  if (!versionNameRegex.test(gradle)) {
    fail('Could not find versionName in android/app/build.gradle');
  }

  gradle = gradle.replace(versionNameRegex, `$1${version}$3`);

  writeFileSync(gradlePath, gradle, 'utf8');
  log(`Updated Android versionName to ${version}`);
}

function updateIosVersion(version) {
  const pbxprojPath = resolve(
    ROOT,
    'ios',
    'App',
    'App.xcodeproj',
    'project.pbxproj'
  );
  let pbx = readFileSync(pbxprojPath, 'utf8');

  const marketingRegex = /(MARKETING_VERSION\s*=\s*)([^;]+)(;)/g;
  if (!marketingRegex.test(pbx)) {
    fail('Could not find MARKETING_VERSION entries in iOS project.pbxproj');
  }

  pbx = pbx.replace(marketingRegex, `$1${version}$3`);

  writeFileSync(pbxprojPath, pbx, 'utf8');
  log(`Updated iOS MARKETING_VERSION to ${version}`);
}

function updateVersionConfig(version) {
  const versionConfigPath = resolve(ROOT, 'src', 'config', 'version.ts');
  const contents =
    `// This file is generated by scripts/release.mjs\n` +
    `// Do not edit manually.\n\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const APP_BUILD_ID = import.meta.env.VITE_APP_BUILD_ID ?? 'dev-local';\n`;

  writeFileSync(versionConfigPath, contents, 'utf8');
  log(`Updated src/config/version.ts APP_VERSION to ${version}`);
}

function main() {
  const version = getVersionArg();
  log(`Releasing version ${version}`);

  updatePackageJson(version);
  updateAndroidVersion(version);
  updateIosVersion(version);
  updateVersionConfig(version);

  log('Version update complete.');
}

main();
